In [97]:
from sklearn.datasets import load_diabetes
from sklearn.ensemble import RandomForestClassifier
from boruta import BorutaPy
import pandas as pd
import numpy as np

In [98]:
market_data = pd.read_csv('./Gap_Target_Final.csv')

In [99]:
market_data.shape

(483, 181)

In [100]:
target = market_data['Gap_Target']

In [101]:
market_data = market_data[market_data.columns[1:-1]]

In [102]:
print(list(market_data.columns))

['Unnamed: 0', '<OPEN>', '<HIGH>', '<LOW>', '<CLOSE>', '<TICKVOL>', '<VOL>', '<SPREAD>', '<DAY>', '<YEAR>', '<WEEKDAY>', '<MONTH>', 'Close', 'RSI', 'RSI_Buy', 'RSI_Sell', 'SMA', 'SMA_Buy', 'SMA_Sell', 'ROC', 'ROC_Buy', 'ROC_Sell', 'EMA', 'EMA_Buy', 'EMA_Sell', 'WMA', 'WMA_Buy', 'WMA_Sell', 'MACD', 'MACD_Buy', 'MACD_Sell', '<CLOSE>X<VOL>', '<CLOSE>2', '<VOL>2', '<CLOSE>XRSI', '<CLOSE>2.1', 'RSI2', '<CLOSE>XSMA', '<CLOSE>2.2', 'SMA2', '<CLOSE>XROC', '<CLOSE>2.3', 'ROC2', '<CLOSE>XEMA', '<CLOSE>2.4', 'EMA2', '<CLOSE>XWMA', '<CLOSE>2.5', 'WMA2', '<CLOSE>XMACD', '<CLOSE>2.6', 'MACD2', 'RSI_Buy_SMA_Buy', 'RSI_Buy_ROC_Buy', 'RSI_Buy_EMA_Buy', 'RSI_Buy_WMA_Buy', 'RSI_Buy_MACD_Buy', 'SMA_Buy_ROC_Buy', 'SMA_Buy_EMA_Buy', 'SMA_Buy_WMA_Buy', 'SMA_Buy_MACD_Buy', 'ROC_Buy_EMA_Buy', 'ROC_Buy_WMA_Buy', 'ROC_Buy_MACD_Buy', 'EMA_Buy_WMA_Buy', 'EMA_Buy_MACD_Buy', 'WMA_Buy_MACD_Buy', 'RSI_Sell_SMA_Sell', 'RSI_Sell_ROC_Sell', 'RSI_Sell_EMA_Sell', 'RSI_Sell_WMA_Sell', 'RSI_Sell_MACD_Sell', 'SMA_Sell_ROC_Sel

In [103]:
#market_data = market_data[['<CLOSE>', '<VOL>', '<OPEN>', '<HIGH>', '<LOW>', 'RSI_Buy', 'RSI_Sell', 'SMA_Buy', 'SMA_Sell', 'ROC_Buy', 'ROC_Sell', 'EMA_Buy', 'EMA_Sell', 'WMA_Buy', 'WMA_Sell', 'MACD', 'MACD_Buy', 'MACD_Sell', '<CLOSE>X<VOL>', '<CLOSE>2', '<VOL>2', '<CLOSE>XMACD', '<CLOSE>2.1', 'MACD2', '<HOUR_SIN>', '<HOUR_COSINE>', '<MINUTE_SIN>', '<MINUTE_COSINE>', '<DAY_SIN>', '<DAY_COSINE>', '<YEAR_SIN>', '<YEAR_COSINE>', '<WEEKDAY_SIN>', '<WEEKDAY_COSINE>', '<MONTH_SIN>', '<MONTH_COSINE>', 'Max<VOL>', 'Mean<VOL>', 'Min<VOL>', 'Std<VOL>', 'Var<VOL>', 'Ptp<VOL>', 'Percentile_10_<VOL>', 'Percentile_60_<VOL>', 'Percentile_90_<VOL>', 'quantile_5_<VOL>', 'quantile_95_<VOL>', 'quantile_99_<VOL>', 'Max<CLOSE>', 'Mean<CLOSE>', 'Min<CLOSE>', 'Std<CLOSE>', 'Var<CLOSE>', 'Ptp<CLOSE>', 'Percentile_10_<CLOSE>', 'Percentile_60_<CLOSE>', 'Percentile_90_<CLOSE>', 'quantile_5_<CLOSE>', 'quantile_95_<CLOSE>', 'quantile_99_<CLOSE>', 'MaxMACD', 'MeanMACD', 'MinMACD', 'StdMACD', 'VarMACD', 'PtpMACD', 'Percentile_10_MACD', 'Percentile_60_MACD', 'Percentile_90_MACD', 'quantile_5_MACD', 'quantile_95_MACD', 'quantile_99_MACD', 'Close_Anterior', 'RSI_Buy_SMA_Buy', 'RSI_Buy_ROC_Buy', 'RSI_Buy_EMA_Buy', 'RSI_Buy_WMA_Buy', 'RSI_Buy_MACD_Buy', 'SMA_Buy_ROC_Buy', 'SMA_Buy_EMA_Buy', 'SMA_Buy_WMA_Buy', 'SMA_Buy_MACD_Buy', 'ROC_Buy_EMA_Buy', 'ROC_Buy_WMA_Buy', 'ROC_Buy_MACD_Buy', 'EMA_Buy_WMA_Buy', 'EMA_Buy_MACD_Buy', 'WMA_Buy_MACD_Buy', 'RSI_Sell_SMA_Sell', 'RSI_Sell_ROC_Sell', 'RSI_Sell_EMA_Sell', 'RSI_Sell_WMA_Sell', 'RSI_Sell_MACD_Sell', 'SMA_Sell_ROC_Sell', 'SMA_Sell_EMA_Sell', 'SMA_Sell_WMA_Sell', 'SMA_Sell_MACD_Sell', 'ROC_Sell_EMA_Sell', 'ROC_Sell_WMA_Sell', 'ROC_Sell_MACD_Sell', 'EMA_Sell_WMA_Sell', 'EMA_Sell_MACD_Sell', 'WMA_Sell_MACD_Sell']]
#all_columns = ['<CLOSE>', '<VOL>', '<OPEN>', '<HIGH>', '<LOW>', 'RSI_Buy', 'RSI_Sell', 'SMA_Buy', 'SMA_Sell', 'ROC_Buy', 'ROC_Sell', 'EMA_Buy', 'EMA_Sell', 'WMA_Buy', 'WMA_Sell', 'MACD', 'MACD_Buy', 'MACD_Sell', '<CLOSE>X<VOL>', '<CLOSE>2', '<VOL>2', '<CLOSE>XMACD', '<CLOSE>2.1', 'MACD2', '<HOUR_SIN>', '<HOUR_COSINE>', '<MINUTE_SIN>', '<MINUTE_COSINE>', '<DAY_SIN>', '<DAY_COSINE>', '<YEAR_SIN>', '<YEAR_COSINE>', '<WEEKDAY_SIN>', '<WEEKDAY_COSINE>', '<MONTH_SIN>', '<MONTH_COSINE>', 'Max<VOL>', 'Mean<VOL>', 'Min<VOL>', 'Std<VOL>', 'Var<VOL>', 'Ptp<VOL>', 'Percentile_10_<VOL>', 'Percentile_60_<VOL>', 'Percentile_90_<VOL>', 'quantile_5_<VOL>', 'quantile_95_<VOL>', 'quantile_99_<VOL>', 'Max<CLOSE>', 'Mean<CLOSE>', 'Min<CLOSE>', 'Std<CLOSE>', 'Var<CLOSE>', 'Ptp<CLOSE>', 'Percentile_10_<CLOSE>', 'Percentile_60_<CLOSE>', 'Percentile_90_<CLOSE>', 'quantile_5_<CLOSE>', 'quantile_95_<CLOSE>', 'quantile_99_<CLOSE>', 'MaxMACD', 'MeanMACD', 'MinMACD', 'StdMACD', 'VarMACD', 'PtpMACD', 'Percentile_10_MACD', 'Percentile_60_MACD', 'Percentile_90_MACD', 'quantile_5_MACD', 'quantile_95_MACD', 'quantile_99_MACD', 'Close_Anterior', 'RSI_Buy_SMA_Buy', 'RSI_Buy_ROC_Buy', 'RSI_Buy_EMA_Buy', 'RSI_Buy_WMA_Buy', 'RSI_Buy_MACD_Buy', 'SMA_Buy_ROC_Buy', 'SMA_Buy_EMA_Buy', 'SMA_Buy_WMA_Buy', 'SMA_Buy_MACD_Buy', 'ROC_Buy_EMA_Buy', 'ROC_Buy_WMA_Buy', 'ROC_Buy_MACD_Buy', 'EMA_Buy_WMA_Buy', 'EMA_Buy_MACD_Buy', 'WMA_Buy_MACD_Buy', 'RSI_Sell_SMA_Sell', 'RSI_Sell_ROC_Sell', 'RSI_Sell_EMA_Sell', 'RSI_Sell_WMA_Sell', 'RSI_Sell_MACD_Sell', 'SMA_Sell_ROC_Sell', 'SMA_Sell_EMA_Sell', 'SMA_Sell_WMA_Sell', 'SMA_Sell_MACD_Sell', 'ROC_Sell_EMA_Sell', 'ROC_Sell_WMA_Sell', 'ROC_Sell_MACD_Sell', 'EMA_Sell_WMA_Sell', 'EMA_Sell_MACD_Sell', 'WMA_Sell_MACD_Sell']

In [104]:
print(list(market_data.columns))

['Unnamed: 0', '<OPEN>', '<HIGH>', '<LOW>', '<CLOSE>', '<TICKVOL>', '<VOL>', '<SPREAD>', '<DAY>', '<YEAR>', '<WEEKDAY>', '<MONTH>', 'Close', 'RSI', 'RSI_Buy', 'RSI_Sell', 'SMA', 'SMA_Buy', 'SMA_Sell', 'ROC', 'ROC_Buy', 'ROC_Sell', 'EMA', 'EMA_Buy', 'EMA_Sell', 'WMA', 'WMA_Buy', 'WMA_Sell', 'MACD', 'MACD_Buy', 'MACD_Sell', '<CLOSE>X<VOL>', '<CLOSE>2', '<VOL>2', '<CLOSE>XRSI', '<CLOSE>2.1', 'RSI2', '<CLOSE>XSMA', '<CLOSE>2.2', 'SMA2', '<CLOSE>XROC', '<CLOSE>2.3', 'ROC2', '<CLOSE>XEMA', '<CLOSE>2.4', 'EMA2', '<CLOSE>XWMA', '<CLOSE>2.5', 'WMA2', '<CLOSE>XMACD', '<CLOSE>2.6', 'MACD2', 'RSI_Buy_SMA_Buy', 'RSI_Buy_ROC_Buy', 'RSI_Buy_EMA_Buy', 'RSI_Buy_WMA_Buy', 'RSI_Buy_MACD_Buy', 'SMA_Buy_ROC_Buy', 'SMA_Buy_EMA_Buy', 'SMA_Buy_WMA_Buy', 'SMA_Buy_MACD_Buy', 'ROC_Buy_EMA_Buy', 'ROC_Buy_WMA_Buy', 'ROC_Buy_MACD_Buy', 'EMA_Buy_WMA_Buy', 'EMA_Buy_MACD_Buy', 'WMA_Buy_MACD_Buy', 'RSI_Sell_SMA_Sell', 'RSI_Sell_ROC_Sell', 'RSI_Sell_EMA_Sell', 'RSI_Sell_WMA_Sell', 'RSI_Sell_MACD_Sell', 'SMA_Sell_ROC_Sel

In [105]:
categorical_columns = ['RSI_Buy_SMA_Buy', 'RSI_Buy_ROC_Buy', 'RSI_Buy_EMA_Buy', 'RSI_Buy_WMA_Buy', 
                       'RSI_Buy_MACD_Buy', 'SMA_Buy_ROC_Buy', 'SMA_Buy_EMA_Buy', 'SMA_Buy_WMA_Buy',
                       'SMA_Buy_MACD_Buy', 'ROC_Buy_EMA_Buy', 'ROC_Buy_WMA_Buy', 'ROC_Buy_MACD_Buy', 
                       'EMA_Buy_WMA_Buy', 'EMA_Buy_MACD_Buy', 'WMA_Buy_MACD_Buy', 'RSI_Sell_SMA_Sell',
                       'RSI_Sell_ROC_Sell', 'RSI_Sell_EMA_Sell', 'RSI_Sell_WMA_Sell', 'RSI_Sell_MACD_Sell',
                       'SMA_Sell_ROC_Sell', 'SMA_Sell_EMA_Sell', 'SMA_Sell_WMA_Sell', 'SMA_Sell_MACD_Sell', 
                       'ROC_Sell_EMA_Sell', 'ROC_Sell_WMA_Sell', 'ROC_Sell_MACD_Sell', 'EMA_Sell_WMA_Sell', 
                       'EMA_Sell_MACD_Sell', 'WMA_Sell_MACD_Sell']
numerical_columns = [i for i in market_data.columns if i not in categorical_columns]

In [106]:
#categorical_columns = ['RSI_Buy_SMA_Buy', 'RSI_Buy_ROC_Buy']

In [107]:
#market_data = market_data[numerical_columns]

In [108]:
all_columns = market_data.columns

In [109]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

transformers = make_column_transformer(#(OneHotEncoder(), categorical_columns),
                                       (RobustScaler(), numerical_columns))

pipeline = Pipeline([
    ('transformer', transformers)
])

pipeline.fit(market_data)

#pipeline_target = Pipeline([
#    ('transformer', transformers)
#])
#
#pipeline_target.fit(target)

Pipeline(steps=[('transformer',
                 ColumnTransformer(transformers=[('robustscaler',
                                                  RobustScaler(),
                                                  ['Unnamed: 0', '<OPEN>',
                                                   '<HIGH>', '<LOW>', '<CLOSE>',
                                                   '<TICKVOL>', '<VOL>',
                                                   '<SPREAD>', '<DAY>',
                                                   '<YEAR>', '<WEEKDAY>',
                                                   '<MONTH>', 'Close', 'RSI',
                                                   'RSI_Buy', 'RSI_Sell', 'SMA',
                                                   'SMA_Buy', 'SMA_Sell', 'ROC',
                                                   'ROC_Buy', 'ROC_Sell', 'EMA',
                                                   'EMA_Buy', 'EMA_Sell', 'WMA',
                                                   'WMA_Buy', 'WMA_Sell',
                                                   'MACD', 'MACD_Buy', ...])]))])

In [110]:
market_data = pipeline.fit_transform(market_data)
#target = pipeline_target.fit_transform(target)

In [111]:
market_data

array([[-1.08490821, -1.23296851, -1.25595103, ..., -0.56127077,
        -0.58450345, -1.23638064],
       [-1.08083542, -1.21867322, -1.24824303, ..., -0.48962568,
        -0.34152576, -1.25695581],
       [-1.07268983, -1.20214429, -1.22919973, ..., -0.38935796,
        -0.47812699, -1.17091419],
       ...,
       [ 1.03135289, -0.20549475, -0.21128996, ..., -0.65631785,
        -0.72092383, -0.23661445],
       [ 1.04425641, -0.13267813, -0.14418499, ..., -0.82543596,
        -0.85918391, -0.1790975 ],
       [ 1.04855758, -0.40473531, -0.39446837, ..., -0.67642338,
        -0.68917612, -0.43675473]])

In [112]:
market_data.shape

(483, 149)

In [113]:
target.ravel()

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [114]:


# let's load the load_diabetes() dataset from sklearn
X, y = market_data, target.ravel()

# let's initialize a RF model 
model = RandomForestClassifier(n_jobs=-1, class_weight='balanced', max_depth=5)

# let's initialize Boruta
feat_selector = BorutaPy(
    verbose=3,
    estimator=model,
    n_estimators='auto',
    max_iter=250,  # number of iterations to perform
    alpha =0.35
)

# train Boruta
# N.B.: X and y must be numpy arrays
feat_selector.fit(np.array(X), np.array(y))

Iteration: 	1 / 250
Confirmed: 	0
Tentative: 	149
Rejected: 	0
Iteration: 	2 / 250
Confirmed: 	0
Tentative: 	149
Rejected: 	0
Iteration: 	3 / 250
Confirmed: 	0
Tentative: 	149
Rejected: 	0
Iteration: 	4 / 250
Confirmed: 	0
Tentative: 	19
Rejected: 	130
Iteration: 	5 / 250
Confirmed: 	10
Tentative: 	9
Rejected: 	130
Iteration: 	6 / 250
Confirmed: 	10
Tentative: 	9
Rejected: 	130
Iteration: 	7 / 250
Confirmed: 	10
Tentative: 	9
Rejected: 	130
Iteration: 	8 / 250
Confirmed: 	10
Tentative: 	7
Rejected: 	132
Iteration: 	9 / 250
Confirmed: 	10
Tentative: 	7
Rejected: 	132
Iteration: 	10 / 250
Confirmed: 	10
Tentative: 	7
Rejected: 	132
Iteration: 	11 / 250
Confirmed: 	10
Tentative: 	7
Rejected: 	132
Iteration: 	12 / 250
Confirmed: 	10
Tentative: 	7
Rejected: 	132
Iteration: 	13 / 250
Confirmed: 	10
Tentative: 	7
Rejected: 	132
Iteration: 	14 / 250
Confirmed: 	10
Tentative: 	7
Rejected: 	132
Iteration: 	15 / 250
Confirmed: 	10
Tentative: 	6
Rejected: 	133
Iteration: 	16 / 250
Confirmed: 	10
T

BorutaPy(alpha=0.35,
         estimator=RandomForestClassifier(class_weight='balanced', max_depth=5,
                                          n_estimators=93, n_jobs=-1,
                                          random_state=RandomState(MT19937) at 0x15B34247440),
         max_iter=250, n_estimators='auto',
         random_state=RandomState(MT19937) at 0x15B34247440, verbose=3)

In [115]:
# check selected features - first 5 features are selected
feat_selector.support_

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False,  True, False, False, False,  True,  True, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False, False, False, False,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [116]:
for i in range(len(feat_selector.support_)):
    if feat_selector.support_[i] == True:
        print(all_columns[i])

RSI
ROC
EMA_Buy
EMA_Sell
WMA_Sell
<CLOSE>2.1
RSI2
<CLOSE>2.3
ROC2
RSI_Sell_EMA_Sell


In [117]:
for i in range(len(feat_selector.support_)):
    if feat_selector.ranking_[i] in [i for i in range(1,5)]:
        print(all_columns[i])

RSI
RSI_Buy
ROC
EMA_Buy
EMA_Sell
WMA_Buy
WMA_Sell
<CLOSE>2.1
RSI2
<CLOSE>2.3
ROC2
RSI_Sell_EMA_Sell
WMA_Sell_MACD_Sell


In [118]:
# check ranking of features
print(feat_selector.ranking_)

[ 44  80  95 130 104  55  45 139 114 140 136 116  94   1   4  11 114   8
   7   1   5   5 108   1   1 118   2   1  12  48  25  82  66  70  97   1
   1 133 126 131 114   1   1 120 106 127  83  90  76  93  13  30  62  69
  53  59  48  48  77  97  42  85  38 112 136 122  99  10   9   1 138 135
 124 101 134 129  17  20  19  14  18   3  24  34  22  33  16  26  23  21
  74  75  66  29  55  27  52  36  32  27 121  84  66 101  99  89 119  80
 103  60  78  91 104  78 110  96  61  14  58 106 117 124 123 132  86  43
  31  48  41 108  39  37  70  35  73  57  62  88  64 110  87  92  51  53
  72  68  46  40 128]


In [119]:
# call transform() on X to filter it down to selected features
X_filtered = feat_selector.transform(X)
X_filtered.shape

(483, 10)

In [120]:
import pickle
with open('market_data.pkl', mode = 'wb') as f:
  pickle.dump([X_filtered, y], f)