In [1]:
from sklearn.datasets import load_diabetes
from sklearn.ensemble import RandomForestClassifier
from boruta import BorutaPy
import pandas as pd
import numpy as np

In [2]:
market_data = pd.read_csv('./Gap_Target_Final.csv')

In [3]:
market_data.shape

(420, 181)

In [4]:
target = market_data['Gap_Target']

In [5]:
market_data = market_data[market_data.columns[1:-1]]

In [6]:
print(list(market_data.columns))

['Unnamed: 0', '<OPEN>', '<HIGH>', '<LOW>', '<CLOSE>', '<TICKVOL>', '<VOL>', '<SPREAD>', '<DAY>', '<YEAR>', '<WEEKDAY>', '<MONTH>', 'Close', 'RSI', 'RSI_Buy', 'RSI_Sell', 'SMA', 'SMA_Buy', 'SMA_Sell', 'ROC', 'ROC_Buy', 'ROC_Sell', 'EMA', 'EMA_Buy', 'EMA_Sell', 'WMA', 'WMA_Buy', 'WMA_Sell', 'MACD', 'MACD_Buy', 'MACD_Sell', '<CLOSE>X<VOL>', '<CLOSE>2', '<VOL>2', '<CLOSE>XRSI', '<CLOSE>2.1', 'RSI2', '<CLOSE>XSMA', '<CLOSE>2.2', 'SMA2', '<CLOSE>XROC', '<CLOSE>2.3', 'ROC2', '<CLOSE>XEMA', '<CLOSE>2.4', 'EMA2', '<CLOSE>XWMA', '<CLOSE>2.5', 'WMA2', '<CLOSE>XMACD', '<CLOSE>2.6', 'MACD2', 'RSI_Buy_SMA_Buy', 'RSI_Buy_ROC_Buy', 'RSI_Buy_EMA_Buy', 'RSI_Buy_WMA_Buy', 'RSI_Buy_MACD_Buy', 'SMA_Buy_ROC_Buy', 'SMA_Buy_EMA_Buy', 'SMA_Buy_WMA_Buy', 'SMA_Buy_MACD_Buy', 'ROC_Buy_EMA_Buy', 'ROC_Buy_WMA_Buy', 'ROC_Buy_MACD_Buy', 'EMA_Buy_WMA_Buy', 'EMA_Buy_MACD_Buy', 'WMA_Buy_MACD_Buy', 'RSI_Sell_SMA_Sell', 'RSI_Sell_ROC_Sell', 'RSI_Sell_EMA_Sell', 'RSI_Sell_WMA_Sell', 'RSI_Sell_MACD_Sell', 'SMA_Sell_ROC_Sel

In [7]:
#market_data = market_data[['<CLOSE>', '<VOL>', '<OPEN>', '<HIGH>', '<LOW>', 'RSI_Buy', 'RSI_Sell', 'SMA_Buy', 'SMA_Sell', 'ROC_Buy', 'ROC_Sell', 'EMA_Buy', 'EMA_Sell', 'WMA_Buy', 'WMA_Sell', 'MACD', 'MACD_Buy', 'MACD_Sell', '<CLOSE>X<VOL>', '<CLOSE>2', '<VOL>2', '<CLOSE>XMACD', '<CLOSE>2.1', 'MACD2', '<HOUR_SIN>', '<HOUR_COSINE>', '<MINUTE_SIN>', '<MINUTE_COSINE>', '<DAY_SIN>', '<DAY_COSINE>', '<YEAR_SIN>', '<YEAR_COSINE>', '<WEEKDAY_SIN>', '<WEEKDAY_COSINE>', '<MONTH_SIN>', '<MONTH_COSINE>', 'Max<VOL>', 'Mean<VOL>', 'Min<VOL>', 'Std<VOL>', 'Var<VOL>', 'Ptp<VOL>', 'Percentile_10_<VOL>', 'Percentile_60_<VOL>', 'Percentile_90_<VOL>', 'quantile_5_<VOL>', 'quantile_95_<VOL>', 'quantile_99_<VOL>', 'Max<CLOSE>', 'Mean<CLOSE>', 'Min<CLOSE>', 'Std<CLOSE>', 'Var<CLOSE>', 'Ptp<CLOSE>', 'Percentile_10_<CLOSE>', 'Percentile_60_<CLOSE>', 'Percentile_90_<CLOSE>', 'quantile_5_<CLOSE>', 'quantile_95_<CLOSE>', 'quantile_99_<CLOSE>', 'MaxMACD', 'MeanMACD', 'MinMACD', 'StdMACD', 'VarMACD', 'PtpMACD', 'Percentile_10_MACD', 'Percentile_60_MACD', 'Percentile_90_MACD', 'quantile_5_MACD', 'quantile_95_MACD', 'quantile_99_MACD', 'Close_Anterior', 'RSI_Buy_SMA_Buy', 'RSI_Buy_ROC_Buy', 'RSI_Buy_EMA_Buy', 'RSI_Buy_WMA_Buy', 'RSI_Buy_MACD_Buy', 'SMA_Buy_ROC_Buy', 'SMA_Buy_EMA_Buy', 'SMA_Buy_WMA_Buy', 'SMA_Buy_MACD_Buy', 'ROC_Buy_EMA_Buy', 'ROC_Buy_WMA_Buy', 'ROC_Buy_MACD_Buy', 'EMA_Buy_WMA_Buy', 'EMA_Buy_MACD_Buy', 'WMA_Buy_MACD_Buy', 'RSI_Sell_SMA_Sell', 'RSI_Sell_ROC_Sell', 'RSI_Sell_EMA_Sell', 'RSI_Sell_WMA_Sell', 'RSI_Sell_MACD_Sell', 'SMA_Sell_ROC_Sell', 'SMA_Sell_EMA_Sell', 'SMA_Sell_WMA_Sell', 'SMA_Sell_MACD_Sell', 'ROC_Sell_EMA_Sell', 'ROC_Sell_WMA_Sell', 'ROC_Sell_MACD_Sell', 'EMA_Sell_WMA_Sell', 'EMA_Sell_MACD_Sell', 'WMA_Sell_MACD_Sell']]
#all_columns = ['<CLOSE>', '<VOL>', '<OPEN>', '<HIGH>', '<LOW>', 'RSI_Buy', 'RSI_Sell', 'SMA_Buy', 'SMA_Sell', 'ROC_Buy', 'ROC_Sell', 'EMA_Buy', 'EMA_Sell', 'WMA_Buy', 'WMA_Sell', 'MACD', 'MACD_Buy', 'MACD_Sell', '<CLOSE>X<VOL>', '<CLOSE>2', '<VOL>2', '<CLOSE>XMACD', '<CLOSE>2.1', 'MACD2', '<HOUR_SIN>', '<HOUR_COSINE>', '<MINUTE_SIN>', '<MINUTE_COSINE>', '<DAY_SIN>', '<DAY_COSINE>', '<YEAR_SIN>', '<YEAR_COSINE>', '<WEEKDAY_SIN>', '<WEEKDAY_COSINE>', '<MONTH_SIN>', '<MONTH_COSINE>', 'Max<VOL>', 'Mean<VOL>', 'Min<VOL>', 'Std<VOL>', 'Var<VOL>', 'Ptp<VOL>', 'Percentile_10_<VOL>', 'Percentile_60_<VOL>', 'Percentile_90_<VOL>', 'quantile_5_<VOL>', 'quantile_95_<VOL>', 'quantile_99_<VOL>', 'Max<CLOSE>', 'Mean<CLOSE>', 'Min<CLOSE>', 'Std<CLOSE>', 'Var<CLOSE>', 'Ptp<CLOSE>', 'Percentile_10_<CLOSE>', 'Percentile_60_<CLOSE>', 'Percentile_90_<CLOSE>', 'quantile_5_<CLOSE>', 'quantile_95_<CLOSE>', 'quantile_99_<CLOSE>', 'MaxMACD', 'MeanMACD', 'MinMACD', 'StdMACD', 'VarMACD', 'PtpMACD', 'Percentile_10_MACD', 'Percentile_60_MACD', 'Percentile_90_MACD', 'quantile_5_MACD', 'quantile_95_MACD', 'quantile_99_MACD', 'Close_Anterior', 'RSI_Buy_SMA_Buy', 'RSI_Buy_ROC_Buy', 'RSI_Buy_EMA_Buy', 'RSI_Buy_WMA_Buy', 'RSI_Buy_MACD_Buy', 'SMA_Buy_ROC_Buy', 'SMA_Buy_EMA_Buy', 'SMA_Buy_WMA_Buy', 'SMA_Buy_MACD_Buy', 'ROC_Buy_EMA_Buy', 'ROC_Buy_WMA_Buy', 'ROC_Buy_MACD_Buy', 'EMA_Buy_WMA_Buy', 'EMA_Buy_MACD_Buy', 'WMA_Buy_MACD_Buy', 'RSI_Sell_SMA_Sell', 'RSI_Sell_ROC_Sell', 'RSI_Sell_EMA_Sell', 'RSI_Sell_WMA_Sell', 'RSI_Sell_MACD_Sell', 'SMA_Sell_ROC_Sell', 'SMA_Sell_EMA_Sell', 'SMA_Sell_WMA_Sell', 'SMA_Sell_MACD_Sell', 'ROC_Sell_EMA_Sell', 'ROC_Sell_WMA_Sell', 'ROC_Sell_MACD_Sell', 'EMA_Sell_WMA_Sell', 'EMA_Sell_MACD_Sell', 'WMA_Sell_MACD_Sell']

In [8]:
print(list(market_data.columns))

['Unnamed: 0', '<OPEN>', '<HIGH>', '<LOW>', '<CLOSE>', '<TICKVOL>', '<VOL>', '<SPREAD>', '<DAY>', '<YEAR>', '<WEEKDAY>', '<MONTH>', 'Close', 'RSI', 'RSI_Buy', 'RSI_Sell', 'SMA', 'SMA_Buy', 'SMA_Sell', 'ROC', 'ROC_Buy', 'ROC_Sell', 'EMA', 'EMA_Buy', 'EMA_Sell', 'WMA', 'WMA_Buy', 'WMA_Sell', 'MACD', 'MACD_Buy', 'MACD_Sell', '<CLOSE>X<VOL>', '<CLOSE>2', '<VOL>2', '<CLOSE>XRSI', '<CLOSE>2.1', 'RSI2', '<CLOSE>XSMA', '<CLOSE>2.2', 'SMA2', '<CLOSE>XROC', '<CLOSE>2.3', 'ROC2', '<CLOSE>XEMA', '<CLOSE>2.4', 'EMA2', '<CLOSE>XWMA', '<CLOSE>2.5', 'WMA2', '<CLOSE>XMACD', '<CLOSE>2.6', 'MACD2', 'RSI_Buy_SMA_Buy', 'RSI_Buy_ROC_Buy', 'RSI_Buy_EMA_Buy', 'RSI_Buy_WMA_Buy', 'RSI_Buy_MACD_Buy', 'SMA_Buy_ROC_Buy', 'SMA_Buy_EMA_Buy', 'SMA_Buy_WMA_Buy', 'SMA_Buy_MACD_Buy', 'ROC_Buy_EMA_Buy', 'ROC_Buy_WMA_Buy', 'ROC_Buy_MACD_Buy', 'EMA_Buy_WMA_Buy', 'EMA_Buy_MACD_Buy', 'WMA_Buy_MACD_Buy', 'RSI_Sell_SMA_Sell', 'RSI_Sell_ROC_Sell', 'RSI_Sell_EMA_Sell', 'RSI_Sell_WMA_Sell', 'RSI_Sell_MACD_Sell', 'SMA_Sell_ROC_Sel

In [9]:
categorical_columns = ['RSI_Buy_SMA_Buy', 'RSI_Buy_ROC_Buy', 'RSI_Buy_EMA_Buy', 'RSI_Buy_WMA_Buy', 
                       'RSI_Buy_MACD_Buy', 'SMA_Buy_ROC_Buy', 'SMA_Buy_EMA_Buy', 'SMA_Buy_WMA_Buy',
                       'SMA_Buy_MACD_Buy', 'ROC_Buy_EMA_Buy', 'ROC_Buy_WMA_Buy', 'ROC_Buy_MACD_Buy', 
                       'EMA_Buy_WMA_Buy', 'EMA_Buy_MACD_Buy', 'WMA_Buy_MACD_Buy', 'RSI_Sell_SMA_Sell',
                       'RSI_Sell_ROC_Sell', 'RSI_Sell_EMA_Sell', 'RSI_Sell_WMA_Sell', 'RSI_Sell_MACD_Sell',
                       'SMA_Sell_ROC_Sell', 'SMA_Sell_EMA_Sell', 'SMA_Sell_WMA_Sell', 'SMA_Sell_MACD_Sell', 
                       'ROC_Sell_EMA_Sell', 'ROC_Sell_WMA_Sell', 'ROC_Sell_MACD_Sell', 'EMA_Sell_WMA_Sell', 
                       'EMA_Sell_MACD_Sell', 'WMA_Sell_MACD_Sell']
numerical_columns = [i for i in market_data.columns if i not in categorical_columns]

In [10]:
#categorical_columns = ['RSI_Buy_SMA_Buy', 'RSI_Buy_ROC_Buy']

In [11]:
#market_data = market_data[numerical_columns]

In [12]:
all_columns = market_data.columns

In [13]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

transformers = make_column_transformer(#(OneHotEncoder(), categorical_columns),
                                       (RobustScaler(), numerical_columns))

pipeline = Pipeline([
    ('transformer', transformers)
])

pipeline.fit(market_data)

#pipeline_target = Pipeline([
#    ('transformer', transformers)
#])
#
#pipeline_target.fit(target)

Pipeline(steps=[('transformer',
                 ColumnTransformer(transformers=[('robustscaler',
                                                  RobustScaler(),
                                                  ['Unnamed: 0', '<OPEN>',
                                                   '<HIGH>', '<LOW>', '<CLOSE>',
                                                   '<TICKVOL>', '<VOL>',
                                                   '<SPREAD>', '<DAY>',
                                                   '<YEAR>', '<WEEKDAY>',
                                                   '<MONTH>', 'Close', 'RSI',
                                                   'RSI_Buy', 'RSI_Sell', 'SMA',
                                                   'SMA_Buy', 'SMA_Sell', 'ROC',
                                                   'ROC_Buy', 'ROC_Sell', 'EMA',
                                                   'EMA_Buy', 'EMA_Sell', 'WMA',
                                                   'WMA_Buy', 'WMA_Sell',
                                                   'MACD', 'MACD_Buy', ...])]))])

In [14]:
market_data = pipeline.fit_transform(market_data)
#target = pipeline_target.fit_transform(target)

In [15]:
market_data

array([[-1.09805949, -1.15086957, -1.17595049, ..., -0.59031119,
        -0.60546316, -1.18518519],
       [-1.09396171, -1.13695652, -1.16843501, ..., -0.51781476,
        -0.35963861, -1.20530407],
       [-1.08576615, -1.12086957, -1.14986737, ..., -0.41635559,
        -0.49784034, -1.12117055],
       ...,
       [ 1.00954744, -0.32782609, -0.33465959, ...,  1.26098275,
         1.47048858, -0.39506173],
       [ 1.04416794, -0.08      , -0.09195402, ..., -0.85761538,
        -0.88336193, -0.15134888],
       [ 1.0484955 , -0.34478261, -0.33598585, ..., -0.70683213,
        -0.71136223, -0.40329218]])

In [16]:
market_data.shape

(420, 149)

In [17]:
target.ravel()

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [18]:


# let's load the load_diabetes() dataset from sklearn
X, y = market_data, target.ravel()

# let's initialize a RF model 
model = RandomForestClassifier(n_jobs=-1, class_weight='balanced', max_depth=5)

# let's initialize Boruta
feat_selector = BorutaPy(
    verbose=3,
    estimator=model,
    n_estimators='auto',
    max_iter=250,  # number of iterations to perform
    alpha =0.35
)

# train Boruta
# N.B.: X and y must be numpy arrays
feat_selector.fit(np.array(X), np.array(y))

Iteration: 	1 / 250
Confirmed: 	0
Tentative: 	149
Rejected: 	0
Iteration: 	2 / 250
Confirmed: 	0
Tentative: 	149
Rejected: 	0
Iteration: 	3 / 250
Confirmed: 	0
Tentative: 	149
Rejected: 	0
Iteration: 	4 / 250
Confirmed: 	0
Tentative: 	17
Rejected: 	132
Iteration: 	5 / 250
Confirmed: 	9
Tentative: 	8
Rejected: 	132
Iteration: 	6 / 250
Confirmed: 	9
Tentative: 	8
Rejected: 	132
Iteration: 	7 / 250
Confirmed: 	9
Tentative: 	8
Rejected: 	132
Iteration: 	8 / 250
Confirmed: 	9
Tentative: 	8
Rejected: 	132
Iteration: 	9 / 250
Confirmed: 	9
Tentative: 	8
Rejected: 	132
Iteration: 	10 / 250
Confirmed: 	9
Tentative: 	8
Rejected: 	132
Iteration: 	11 / 250
Confirmed: 	9
Tentative: 	8
Rejected: 	132
Iteration: 	12 / 250
Confirmed: 	9
Tentative: 	7
Rejected: 	133
Iteration: 	13 / 250
Confirmed: 	9
Tentative: 	7
Rejected: 	133
Iteration: 	14 / 250
Confirmed: 	9
Tentative: 	7
Rejected: 	133
Iteration: 	15 / 250
Confirmed: 	9
Tentative: 	5
Rejected: 	135
Iteration: 	16 / 250
Confirmed: 	9
Tentative: 	5

BorutaPy(alpha=0.35,
         estimator=RandomForestClassifier(class_weight='balanced', max_depth=5,
                                          n_estimators=93, n_jobs=-1,
                                          random_state=RandomState(MT19937) at 0x1EB80337440),
         max_iter=250, n_estimators='auto',
         random_state=RandomState(MT19937) at 0x1EB80337440, verbose=3)

In [19]:
# check selected features - first 5 features are selected
feat_selector.support_

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False,  True, False, False, False,  True,  True, False, False,
       False, False, False, False, False, False, False, False,  True,
        True, False, False, False, False,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [20]:
for i in range(len(feat_selector.support_)):
    if feat_selector.support_[i] == True:
        print(all_columns[i])

RSI
ROC
EMA_Buy
EMA_Sell
<CLOSE>2.1
RSI2
<CLOSE>2.3
ROC2
RSI_Sell_EMA_Sell


In [21]:
for i in range(len(feat_selector.support_)):
    if feat_selector.ranking_[i] in [i for i in range(1,5)]:
        print(all_columns[i])

RSI
RSI_Buy
ROC
EMA_Buy
EMA_Sell
WMA_Buy
WMA_Sell
<CLOSE>2.1
RSI2
<CLOSE>2.3
ROC2
RSI_Sell_ROC_Sell
RSI_Sell_EMA_Sell


In [22]:
# check ranking of features
print(feat_selector.ranking_)

[ 35 111  76 106  84  74  56 140  71 141 139 138 137   1   4  17 134   8
   8   1   6   6 126   1   1 130   4   4  12 113  55 115  57  48 103   1
   1  94 104 123 108   1   1  87 120 118 113 125  99  79  13  35 101  84
  81  34  44 109  38  66  32  70  42  65 135 123 117  10   2   1  99 132
 136 128 121 105  22  25  24  14  14  10  33  28  19  64  16  29  21  44
  71  50  44  18  46  30  47  41  27  31  73  91 102  94  91  89  77  96
  84  68 110 122 132  91  53  51  58  19 119 132 116  99  88 127  63  48
  22  74 107  69  38  79  77  25  58  60  60  37  86  91  97 112  40  82
  66  52  54  62 129]


In [23]:
# call transform() on X to filter it down to selected features
X_filtered = feat_selector.transform(X)
X_filtered.shape

(420, 9)

In [24]:
import pickle
with open('market_data.pkl', mode = 'wb') as f:
  pickle.dump([X_filtered, y], f)